// generated by Fast Light User Interface Designer (fluid) version 1.0302

#ifndef rollingui_h
#define rollingui_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include "rollingview.h"
#include <FL/Fl_Menu_Bar.H>
#include <FL/Fl_Group.H>

class RollingUI {
public:
  RollingUI();
  Fl_Double_Window *window;
  RollingView *scene_view;
  static Fl_Menu_Item menu_[];
  static Fl_Menu_Item *file_menu;
  static Fl_Menu_Item *file_new_button;
  Fl_Group *status_bar;
  void show();
};
#endif
