// generated by Fast Light User Interface Designer (fluid) version 1.0302

#ifndef rollingui_h
#define rollingui_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Roller.H>
#include <FL/Fl_Slider.H>
#include "RollingView.h"
#include <FL/Fl_Value_Slider.H>

class RollingUI {
public:
  RollingUI();
  Fl_Group *VChange;
  Fl_Roller *vrot;
  Fl_Slider *ypan;
  Fl_Group *HChange;
  Fl_Roller *hrot;
  Fl_Slider *xpan;
  Fl_Group *MainView;
  RollingView *scene_view;
  Fl_Value_Slider *zoom;
};
#endif
